cmake_minimum_required(VERSION 3.22)

execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_REV_PARSE
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

string(TIMESTAMP TODAY "%Y_%m_%d %H:%M")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG.md"
    "${CMAKE_BINARY_DIR}/CHANGELOG.md")

install(FILES ${CMAKE_BINARY_DIR}/CHANGELOG.md DESTINATION .)
